---
- name: Generate Kubernetes YAML file
  ansible.builtin.template:
    src: ut2-server.yml.j2
    dest: /etc/containers/systemd/ut2-server-{{ server_id }}.yml
    mode: "0644"
  register: server_kubernetes_yaml
  become: true

- name: Generate Quadlet network
  ansible.builtin.template:
    src: ut2-server.network.j2
    dest: /etc/containers/systemd/ut2-server.network
    mode: "0644"
  become: true

- name: Generate Quadlet kube
  ansible.builtin.template:
    src: ut2-server.kube.j2
    dest: /etc/containers/systemd/ut2-server-{{ server_id }}.kube
    mode: "0644"
  register: server_quadlet_kube
  become: true

- name: Open up server ports
  ansible.posix.firewalld:
    port: "{{ item }}"
    zone: public
    state: enabled
    immediate: true
    permanent: true
  become: true
  loop:
    - "{{ server_game_port }}/udp"
    - "{{ server_query_port }}/udp"
    - "{{ server_gamespy_query_port }}/udp"
    - "{{ server_web_admin_port }}/tcp"

# This may take a while as it pulls down the image, so run async and check on
# the result later.
- name: Start or Restart the server
  ansible.builtin.systemd:
    name: "ut2-server-{{ server_id }}.service"
    daemon_reload: true
    state: "{{ server_kubernetes_yaml.changed or server_quadlet_kube.changed | ternary('restarted', 'started') }}"
    enabled: true
  become: true
  async: 45
  poll: 0
  register: server_start_job

- name: Wait on server start result
  ansible.builtin.async_status:
    jid: "{{ server_start_job.ansible_job_id }}"
  become: true
  register: server_start_job_result
  until: server_start_job_result.finished
  retries: 100
  delay: 10
