---
- name: Provision UT2004 Servers
  hosts: ut2_server
  vars_files:
    - config.yml

  tasks:
    - name: Pull down server container
      containers.podman.podman_image:
        name: "{{ ut2_server_image }}"
      become: true
      async: 900
      poll: 0
      register: pull_containers

    - name: Wait for pull
      ansible.builtin.async_status:
        jid: "{{ pull_containers.ansible_job_id }}"
      become: true
      register: pull_containers_result
      until: pull_containers_result.finished
      retries: 90
      delay: 10

    - name: Create instance
      ansible.builtin.include_role:
        name: ut2_server
      vars:
        ut2_server_id: "{{ server_item - 1 }}"
        ut2_server_game_port: "{{ 7777 + (20 * server_item) }}"
        ut2_server_web_admin_port: "{{ 8000 + (20 * server_item) }}"
      loop: "{{ server_instances }}"
      loop_control:
        loop_var: server_item
