---
- name: Provision UT2004 Servers
  hosts: ut2_server
  vars:
    ut2004_server_image: ghcr.io/aldehir/ut2004-server:3369.3-release-1

  tasks:
    - name: Pull down server container
      containers.podman.podman_image:
        name: "{{ ut2004_server_image }}"

    - name: Create server pod for instance 1
      ansible.builtin.include_role:
        name: ut2_server
      vars:
        ut2_server_id: 1
        ut2_server_image: "{{ ut2004_server_image }}"
        ut2_server_game_port: 7777
        ut2_server_web_admin_port: 8000

    - name: Create server pod for instance 2
      ansible.builtin.include_role:
        name: ut2_server
      vars:
        ut2_server_id: 2
        ut2_server_image: "{{ ut2004_server_image }}"
        ut2_server_game_port: 7797
        ut2_server_web_admin_port: 8001

    - name: Create server pod for instance 3
      ansible.builtin.include_role:
        name: ut2_server
      vars:
        ut2_server_id: 3
        ut2_server_image: "{{ ut2004_server_image }}"
        ut2_server_game_port: 7817
        ut2_server_web_admin_port: 8002

    - name: Say hello, elevated
      ansible.builtin.debug:
        msg: "Hello from elevated permissions"
      become: true
