---
- name: Provision UT2004 Servers
  hosts: ut2_server
  vars_files:
    - config.yml

  tasks:
    - name: Pull down server container
      containers.podman.podman_image:
        name: "{{ ut2_server_image }}"
      become: true
      async: 900
      poll: 0
      register: pull_containers

    - name: Wait for pull
      ansible.builtin.async_status:
        jid: "{{ pull_containers.ansible_job_id }}"
      become: true
      register: pull_containers_result
      until: pull_containers_result.finished
      retries: 90
      delay: 10

    - name: Create server pod for instance 1
      ansible.builtin.include_role:
        name: ut2_server
      vars:
        ut2_server_id: 1
        ut2_server_game_port: 7777
        ut2_server_web_admin_port: 8000

    - name: Create server pod for instance 2
      ansible.builtin.include_role:
        name: ut2_server
      vars:
        ut2_server_id: 2
        ut2_server_game_port: 7797
        ut2_server_web_admin_port: 8001

    - name: Create server pod for instance 3
      ansible.builtin.include_role:
        name: ut2_server
      vars:
        ut2_server_id: 3
        ut2_server_game_port: 7817
        ut2_server_web_admin_port: 8002
