plugin: community.digitalocean.digitalocean
api_token: "{{ lookup('ansible.builtin.env', 'DIGITALOCEAN_TOKEN') }}"
attributes:
  - id
  - name
  - networks
  - tags
keyed_groups:
  - key: do_tags | lower | replace('-', '_')
    prefix: ''
    separator: ''
compose:
  ansible_ssh_host: do_networks.v4 | selectattr('type', 'eq', 'public') | map(attribute='ip_address') | first

