#!/usr/bin/bash
install -o nginx -g nginx -m 644 "$LEGO_CERT_PATH" /etc/pki/tls/certs/server.crt
install -o nginx -g nginx -m 640 "$LEGO_CERT_KEY_PATH" /etc/pki/tls/private/server.key

cat <<EOF > /etc/nginx/default.d/ssl.conf
ssl_certificate     /etc/pki/tls/certs/server.crt;
ssl_certificate_key /etc/pki/tls/private/server.key;
EOF

chown nginx:nginx /etc/nginx/default.d/ssl.conf
chmod 644 /etc/nginx/default.d/ssl.conf

systemctl reload nginx.service
