# Build the launcher first
FROM docker.io/library/golang:1.21
COPY launcher /src
WORKDIR /src
RUN CGO_ENABLE=0 go build -o /usr/bin/launcher .

# UT2004 container
FROM ghcr.io/aldehir/ut2/base:3369.3-release-2

ARG COMMUNITY_MAPS_URL=https://cdn.alde.dev/ut2k4/packs/ut2004-ufc-community-maps.zip?checksum=sha256:f8e294ae7e990d5a97edca453473477a761477478cb7f5b0e2570095a8067b41

RUN dnf install -y bsdtar && \
    mkdir Community && \
    cd Community && \
    curl -sfL $COMMUNITY_MAPS_URL | bsdtar -x --no-same-owner -vf -

ARG UT2U_VERSION=v0.1.4

ENV UT2_SERVER_NAME="UT2004 Server" \
    UT2_SERVER_ADMIN="" \
    UT2_SERVER_MOTD="" \
    UCC=/opt/ut2004/System/ucc-bin-linux-amd64

COPY --from=0 /usr/bin/launcher /usr/bin/launcher
COPY --chmod=755 entrypoint.sh ./entrypoint.sh

RUN curl -sfL -o /usr/bin/ut2u https://github.com/aldehir/ut2u/releases/download/$UT2U_VERSION/ut2u-linux-amd64 && \
    chmod +x /usr/bin/ut2u && \
    mkdir Config

LABEL org.opencontainers.image.created="2023-09-01T12:00:00Z" \
      org.opencontainers.image.authors="Alde Rojas" \
      org.opencontainers.image.title="UT2004 Dedicated Server - TAM/UTComp Configuration" \
      org.opencontainers.image.description="UT2004 Dedicated Server - TAM/UTComp Configuration" \
      org.opencontainers.image.source="https://github.com/aldehir/ut2.kokuei.dev"

VOLUME ["/opt/ut2004/Config"]

ENTRYPOINT ["/opt/ut2004/entrypoint.sh"]
CMD ["DM-DE-Ironic-FE.ut2"]
