---
- name: Provision UT2004 Servers
  strategy: ansible.builtin.free
  hosts: ut2_server

  tasks:
    # TODO: Move these to the respective provider base images
    - name: Get active tuned profile
      ansible.builtin.command: tuned-adm active
      register: tuned_active_result
      changed_when: false
      become: true

    - name: Set tuned profile to network-latency
      ansible.builtin.command: tuned-adm profile network-latency
      when: '"network-latency" not in tuned_active_result.stdout'
      changed_when: true
      become: true

    - name: Install firewalld and start
      ansible.builtin.package:
        name: firewalld
        state: present
      become: true

    - name: Enable firewalld
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true
      become: true

    - name: Install requirements
      ansible.builtin.package:
        name:
          - python3
          - python3-firewall
          - python3-podman
          - python3-libselinux
        state: present
      become: true

    - name: Create a directory for shared files
      ansible.builtin.file:
        path: /var/lib/ut2004
        state: directory
        mode: "0755"
      become: true

    - name: Generate an XAdmin.ini
      ansible.builtin.template:
        src: XAdmin.ini.j2
        dest: /var/lib/ut2004/XAdmin.ini
        mode: "0600"
      become: true

    - name: Add selinux context for shared directory
      community.general.sefcontext:
        target: '/var/lib/ut2004(/.*)?'
        setype: container_file_t
        state: present
      when: ansible_selinux.mode == "enforcing"
      become: true

    - name: Restore context
      ansible.builtin.command: restorecon -R /var/lib/ut2004
      register: restorecon_result
      when: ansible_selinux.mode == "enforcing"
      changed_when: true
      become: true

    - name: Create instance
      ansible.builtin.include_role:
        name: ut2_server
      vars:
        ut2_server_image: "{{ inst.image | default(server_instance_default_image) }}"
        ut2_server_config_image: "{{ inst.config_image | default(server_instance_default_config_image) }}"
        ut2_server_id: "{{ inst.id }}"
        ut2_server_game_port: "{{ inst.port }}"
        ut2_server_web_admin_port: "{{ inst.admin_port }}"
        ut2_server_info_name: "{{ inst.info.name }}"
        ut2_server_info_admin: "{{ inst.info.admin }}"
      loop: "{{ server_instances }}"
      loop_control:
        loop_var: inst
