---
- name: Provision UT2004 Servers
  hosts: ut2_server

  tasks:
    - name: Get active tuned profile
      ansible.builtin.command: tuned-adm active
      register: tuned_active_result
      changed_when: false
      become: true

    - name: Set tuned profile to network-latency
      ansible.builtin.command: tuned-adm profile network-latency
      when: '"network-latency" not in tuned_active_result.stdout'
      changed_when: true
      become: true

    - name: Install requirements
      ansible.builtin.package:
        name:
          - python3-firewall
          - python3-podman
        state: present
      become: true

    - name: Create instance
      ansible.builtin.include_role:
        name: ut2_server
      vars:
        ut2_server_image: "{{ inst.image | default(server_instance_default_image) }}"
        ut2_server_id: "{{ inst.id }}"
        ut2_server_game_port: "{{ inst.port }}"
        ut2_server_web_admin_port: "{{ inst.admin_port }}"
        ut2_server_info_name: "{{ inst.info.name }}"
        ut2_server_info_admin: "{{ inst.info.admin }}"
      loop: "{{ server_instances }}"
      loop_control:
        loop_var: inst
