---
- name: Provision UT2004 Servers
  hosts: ut2_server

  tasks:
    - name: Create instance
      ansible.builtin.include_role:
        name: ut2_server
      vars:
        ut2_server_id: "{{ server_item + 1 }}"
        ut2_server_game_port: "{{ 7777 + (20 * server_item) }}"
        ut2_server_web_admin_port: "{{ 8000 + server_item }}"
      loop: "{{ range(0, server_instance_count) | list }}"
      loop_control:
        loop_var: server_item
