---
- name: Pull down server container
  containers.podman.podman_image:
    name: "{{ ut2_server_image }}"
    force: true
    pull: true
  become: true
  async: 900
  poll: 0
  register: ut2_server_pull_container

- name: Wait for pull
  ansible.builtin.async_status:
    jid: "{{ ut2_server_pull_container.ansible_job_id }}"
  become: true
  register: ut2_server_pull_container_result
  until: ut2_server_pull_container_result.finished
  retries: 90
  delay: 10

- name: Pull down config container
  containers.podman.podman_image:
    name: "{{ ut2_server_config_image }}"
    force: true
    pull: true
  become: true
  register: ut2_server_pull_config_container

- name: Generate Kubernetes YAML file
  ansible.builtin.template:
    src: ut2-instance.yml.j2
    dest: /etc/containers/systemd/{{ ut2_server_instance_name }}.yml
    mode: "0644"
  register: ut2_generate_kubernetes_yaml_result
  become: true

- name: Generate Quadlet kube
  ansible.builtin.template:
    src: ut2-instance.kube.j2
    dest: /etc/containers/systemd/{{ ut2_server_instance_name }}.kube
    mode: "0644"
  register: ut2_generate_quadlet_result
  become: true

- name: Set restart fact
  ansible.builtin.set_fact:
    ut2_server_restart: >
      ut2_server_pull_container_result.changed or
      ut2_generate_quadlet_result.changed or
      ut2_generate_kubernetes_yaml_result.changed or
      ut2_server_pull_config_container.changed

- name: Open up server ports
  ansible.posix.firewalld:
    port: "{{ item }}"
    zone: public
    state: enabled
    immediate: true
    permanent: true
  become: true
  loop:
    - "{{ ut2_server_game_port }}/udp"
    - "{{ ut2_server_query_port }}/udp"
    - "{{ ut2_server_gamespy_port }}/udp"
    - "{{ ut2_server_web_admin_port }}/tcp"

- name: Restart instance
  ansible.builtin.include_tasks: restart.yml
  when: ut2_server_restart
