---
- name: Pull down server container
  containers.podman.podman_image:
    name: "{{ ut2_server_image }}"
    pull: true
  become: true
  async: 900
  poll: 0
  register: ut2_server_pull_containers

- name: Wait for pull
  ansible.builtin.async_status:
    jid: "{{ ut2_server_pull_containers.ansible_job_id }}"
  notify: Restart instance
  become: true
  register: ut2_server_pull_containers_result
  until: ut2_server_pull_containers_result.finished
  retries: 90
  delay: 10

- name: Generate Kubernetes YAML file
  ansible.builtin.template:
    src: ut2-instance.yml.j2
    dest: /etc/containers/systemd/{{ ut2_server_instance_name }}.yml
    mode: "0644"
  notify: Restart instance
  become: true

- name: Generate Quadlet kube
  ansible.builtin.template:
    src: ut2-instance.kube.j2
    dest: /etc/containers/systemd/{{ ut2_server_instance_name }}.kube
    mode: "0644"
  notify: Restart instance
  become: true

- name: Open up server ports
  ansible.posix.firewalld:
    port: "{{ item }}"
    zone: public
    state: enabled
    immediate: true
    permanent: true
  become: true
  loop:
    - "{{ ut2_server_game_port }}/udp"
    - "{{ ut2_server_query_port }}/udp"
    - "{{ ut2_server_gamespy_port }}/udp"
    - "{{ ut2_server_web_admin_port }}/tcp"

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
