name: Build and Deploy UT2 Servers
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
  push:
    branches: [main]

env:
  IMAGE_REGISTRY: ghcr.io
  IMAGE_TAG: ghcr.io/${{ github.repository_owner }}/ut2/tam-utcomp
  CONFIG_IMAGE_TAG: ghcr.io/${{ github.repository_owner }}/ut2/tam-utcomp-config
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  build-server-image:
    name: Build Server Image
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-container.yml
    with:
      environment: ${{ inputs.environment || 'staging' }}
      image-name: tam-utcomp

  build-config-image:
    name: Build Config Image
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-container.yml
    with:
      environment: ${{ inputs.environment || 'staging' }}
      image-name: tam-utcomp-config

  build-tam-config-image:
    name: Build TAM-only Config Image
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-container.yml
    with:
      environment: ${{ inputs.environment || 'staging' }}
      image-name: tam-only-config

  deploy:
    name: Deploy
    needs: [build-server-image, build-config-image, build-tam-config-image]
    uses: ./.github/workflows/deploy.yml
    with:
      environment: ${{ inputs.environment || 'staging' }}
    secrets: inherit
