name: Build and Deploy UT2 Servers
on:
  push:
    branches: [main]

env:
  IMAGE_REGISTRY: ghcr.io
  IMAGE_TAG: ghcr.io/${{ github.repository_owner }}/ut2/tam-utcomp
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  build:
    name: Build TAM/UTComp Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    outputs:
      container-image: ${{ env.IMAGE_TAG }}:${{ github.sha }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./containers/tam-utcomp
          file: ./containers/tam-utcomp/Containerfile
          tags: |
            ${{ env.IMAGE_TAG }}:${{ github.sha }}
            ${{ env.IMAGE_TAG }}:${{ github.ref_name }}${{ fromJSON('{"dev": "-dev", "production": ""}')[env.PULUMI_STACK] }}
          cache-from: |
            ${{ env.IMAGE_TAG }}:cache
          cache-to: |
            ${{ env.IMAGE_TAG }}:cache
          push: true

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    uses: ./.github/workflows/deploy.yml
    secrets: inherit

  sync-redirect:
    name: Synchronize Redirect
    runs-on: ubuntu-latest
    needs: build
    container:
      image: ${{ needs.build.outputs.container-image }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
      REDIRECT_BUCKET: ${{ vars.REDIRECT_BUCKET }}
      REDIRECT_PREFIX: ${{ vars.REDIRECT_PREFIX }}
    steps:
      - name: Push Packages
        run: /usr/bin/ut2u redirect sync -b $REDIRECT_BUCKET -p $REDIRECT_PREFIX /opt/ut2004/System/UT2004.ini
