name: Deploy
on:
  workflow_dispatch:
  workflow_call:

jobs:
  create-instances:
    name: Create Instances
    uses: ./.github/workflows/pulumi-up.yml
    secrets: inherit

  provision:
    name: Provision
    uses: ./.github/workflows/provision.yml
    secrets: inherit
