name: Deploy
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy-staging:
    name: Deploy [Staging]
    uses: ./.github/workflows/deploy-env.yml
    with:
      environment: staging
    secrets: inherit

  deploy-production:
    name: Deploy [Staging]
    needs: [deploy-staging]
    uses: ./.github/workflows/deploy-env.yml
    with:
      environment: production
    secrets: inherit
