name: On Push
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy-staging:
    name: Deploy Staging
    uses: ./.github/workflows/deploy.yml
    with:
      environment: staging
    secrets: inherit

  deploy-production:
    name: Deploy Production
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
    secrets: inherit
