name: Pulumi Up
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      environment:
        type: string

concurrency: deploy-${{ inputs.environment }}

jobs:
  create-instances:
    name: Pulumi Up
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.11"
          cache: pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: ${{ vars.PULUMI_STACK }}
          work-dir: ./instance
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
