name: Pulumi Destory
on:
  - workflow_dispatch

jobs:
  preview:
    name: Pulumi Destory
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.11"
          cache: pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - uses: pulumi/actions@v3
        with:
          command: destroy
          stack-name: dev
          work-dir: ./instance
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
