name: Pulumi Up
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  create-instances:
    name: Pulumi Up
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.11"
          cache: pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: dev
          work-dir: ./instance
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

  provision-instances:
    uses: ./.github/workflows/provision.yml
