---
- name: Update CA trust
  ansible.builtin.command: update-ca-trust
  changed_when: true
  become: true

- name: Restart nginx
  ansible.builtin.service:
    name: nginx.service
    state: restarted
  become: true

- name: Restart node_exporter
  ansible.builtin.service:
    name: node_exporter.service
    state: restarted
  become: true

- name: Restart promtail
  ansible.builtin.service:
    name: promtail.service
    state: restarted
  become: true

- name: Restart rsyslog
  ansible.builtin.service:
    name: rsyslog.service
    state: restarted
  become: true
